### ISSUE TITLE
Having a problem .

### ISSUE THREAD

**Issue by rmacuna** [craigbuckler/gulp4-css#1]
The compiles version of my app throws me this error. 
GET http://localhost:8000/images/imagenDePrueba.png 404 (Not Found)

My project structure is 

build
 -css 
-images 
node_modules
src
 -images
-js 
-scss 
 -base 
gulpfile.js
index.html 
package-lock.json
package.json
.gitignore

**Comment by craigbuckler** [comment]
Is that file present in the src/images folder?
Is an optimized version copied to the build/images folder when you run Gulp?
Do you get any image errors when running Gulp?

Is there a reason you want to access it directly from the BrowserSync web server?

**Comment by rmacuna** [comment]
Actually, I already have that file in src/images. And yes, an optimized version is copied to build/images folder. I don't get any error when running Gulp. So in _base/base.scss I have an image with resolve(imagename) but the output is images/imagename.png. So in the browser the route localhost:8000/images/myimage.png doesn't exists but if I manually set the path /build/images/myimage.png it works!

**Comment by craigbuckler** [comment]
The configuration is correct in that you should not be referencing the `build` folder in output code since the content of that folder would be copied to a server somewhere. However, browsersync is using the root folder so `index.html` has to reference `build`. Any `resolve()` paths in the CSS therefore fail.

The solution is to copy/construct HTML files in the `build` folder and then set `baseDir : './build/'` in the `syncConfig` setting. But you're then moving beyond the CSS-only scope of this demonstration.

I hope that helps.
